// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "ManualDrive.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

ManualDrive::ManualDrive(): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
	/*
	requires(Robot::drive);
	requires(Robot::oi);
	*/
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void ManualDrive::Initialize() {
}

// Called repeatedly when this Command is scheduled to run
void ManualDrive::Execute() {
	/*
	Robot::drive->MecanumDrive_Cartesian(joystick1->GetX(frc::GenericHID::JoystickHand::kLeftHand),
								   joystick1->GetY(frc::GenericHID::JoystickHand::kLeftHand),
								   joystick1->GetZ(frc::GenericHID::JoystickHand::kLeftHand));
	//driver->MecanumDrive_Cartesian(oi.getJoystick1()->getX(),oi.getJoystick1()->getY(),oi.getJoystick1()->getZ());
	 */
}

// Make this return true when this Command no longer needs to run execute()
bool ManualDrive::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void ManualDrive::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ManualDrive::Interrupted() {

}
